### ISSUE TITLE
Timeout Rate and Last Timeout don't update once node is modified

### ISSUE THREAD

**Issue by treebeard** [geckogecko/storj_hoststats_app#4]
I deleted an old node, and set up a new one with different hardware on the same IP/Port as the old node. However, the app still shows the old node's timeout rate and last timeout, instead of updating with the new information (which is 0 timeout rate).

**Comment by geckogecko** [comment]
Thank you for your report! Can you confirm that your new node has a different nodeID ? Are you just monitoring one node or multiple nodes with the app ? And did you delete your old node and create a new one or did you just edited the nodeID of your old node ?

**Comment by velagand** [comment]
Yes my new node has a different nodeID. I am monitoring multiple nodes with the app. I only edited the nodeID of the old node from what I remember (but I believe I tried deleting and re-adding once I noticed the issue). It seems to be fixed now though.
